# Generated by Django 5.2.8 on 2025-11-18 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chit",
            fields=[
                (
                    "chit_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("chit_name", models.CharField(max_length=255)),
                (
                    "chit_type",
                    models.CharField(
                        choices=[
                            ("Daily", "Daily"),
                            ("Weekly", "Weekly"),
                            ("Monthly", "Monthly"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "chit_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("total_duration", models.IntegerField()),
                ("starting_date", models.DateField()),
                ("ending_date", models.DateField()),
                ("password", models.CharField(max_length=255)),
                ("chit_profile_image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "chits",
                "ordering": ["-created_at"],
            },
        ),
    ]
