# Generated by Django 5.2.8 on 2025-11-18 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "member_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("mobile_number", models.CharField(max_length=10)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("member", "Member"),
                            ("organizer", "Organizer"),
                            ("treasurer", "Treasurer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("profile_image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.chit",
                    ),
                ),
            ],
            options={
                "db_table": "members",
                "ordering": ["-created_at"],
                "unique_together": {("chit", "mobile_number")},
            },
        ),
    ]
