# Generated by Django 5.2.8 on 2025-11-18 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_member"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="password",
            field=models.CharField(default="changeme", max_length=255),
        ),
    ]
