# Generated by Django 5.2.8 on 2025-11-19 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_member_password"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "loan_id",
                    models.CharField(
                        editable=False,
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("loan_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "interest_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("starting_date", models.DateField()),
                ("ending_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="core.chit",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="loans",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "db_table": "loans",
                "ordering": ["-created_at"],
            },
        ),
    ]
