# Generated by Django 5.2.8 on 2025-11-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_loan"),
    ]

    operations = [
        migrations.AddField(
            model_name="loan",
            name="interest_rate",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name="loan",
            name="interest_status",
            field=models.CharField(
                choices=[("paid", "Paid"), ("unpaid", "Unpaid")],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="loan",
            name="loan_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="paid_amount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="loan",
            name="remark",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="loan",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("overdue", "Overdue")],
                default="active",
                max_length=10,
            ),
        ),
    ]
