# Generated by Django 5.2.8 on 2025-11-19 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_loan_interest_rate_loan_interest_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "entry_id",
                    models.CharField(editable=False, max_length=255, unique=True),
                ),
                ("serial_no", models.IntegerField(editable=False)),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "fine",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "loan_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("remark", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField()),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("online", "Online"), ("offline", "Offline")],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.chit",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="core.member",
                    ),
                ),
            ],
            options={
                "db_table": "ledger_entries",
                "ordering": ["-date"],
                "unique_together": {("chit", "serial_no")},
            },
        ),
    ]
